# Generated by Django 5.1 on 2024-11-06 20:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations,  models


class Migration(migrations.Migration):

    dependencies = [
        ('users',  '0001_initial'), 
    ]

    operations = [
        migrations.AddField(
            model_name='profile', 
            name='wallet_balance', 
            field=models.DecimalField(decimal_places=2,  default=500.0,  max_digits=10), 
        ), 
        migrations.AlterField(
            model_name='profile', 
            name='role', 
            field=models.CharField(choices=[('regular',  'Regular User'),  ('theateradmin',  'Theater Admin'),  ('superadmin',  'Super Admin')],  default='regular',  max_length=20), 
        ), 
        migrations.CreateModel(
            name='WalletTransaction', 
            fields=[
                ('id',  models.BigAutoField(auto_created=True,  primary_key=True,  serialize=False,  verbose_name='ID')), 
                ('transaction_type',  models.CharField(choices=[('add',  'Add'),  ('withdraw',  'Withdraw')],  max_length=20)), 
                ('amount',  models.DecimalField(decimal_places=2,  max_digits=10)), 
                ('status',  models.CharField(choices=[('INCOMPLETE',  'Incomplete'),  ('COMPLETE',  'Complete'),  ('REVERTED',  'Reverted')],  max_length=10)), 
                ('timestamp',  models.DateTimeField(default=django.utils.timezone.now)), 
                ('profile',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  to='users.profile')), 
            ], 
        ), 
    ]
