#  Generated by Django 5.1 on 2024-11-12 16:04

from django.db import migrations,  models


class Migration(migrations.Migration):

    dependencies = [
        ('users',  '0002_profile_wallet_balance_alter_profile_role_and_more'), 
    ]

    operations = [
        migrations.AlterField(
            model_name='profile', 
            name='wallet_balance', 
            field=models.DecimalField(decimal_places=2,  default=5000.0,  max_digits=10), 
        ), 
        migrations.DeleteModel(
            name='WalletTransaction', 
        ), 
    ]
