# Generated by Django 5.1 on 2024-11-07 20:05

import django.db.models.deletion
from django.db import migrations,  models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Theaters',  '0001_initial'), 
    ]

    operations = [
        migrations.CreateModel(
            name='Movie', 
            fields=[
                ('id',  models.BigAutoField(auto_created=True,  primary_key=True,  serialize=False,  verbose_name='ID')), 
                ('title',  models.CharField(max_length=255)), 
                ('description',  models.TextField()), 
                ('duration',  models.IntegerField()), 
                ('release_date',  models.DateField()), 
            ], 
        ), 
        migrations.CreateModel(
            name='Show', 
            fields=[
                ('id',  models.BigAutoField(auto_created=True,  primary_key=True,  serialize=False,  verbose_name='ID')), 
                ('start_time',  models.DateTimeField()), 
                ('end_time',  models.DateTimeField()), 
                ('ticket_price',  models.DecimalField(decimal_places=2,  max_digits=6)), 
                ('movie',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  to='Movies.movie')), 
                ('screen',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  to='Theaters.screen')), 
                ('theater',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  to='Theaters.theater')), 
            ], 
        ), 
    ]
