#  Generated by Django 5.1 on 2024-11-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food',  '0002_alter_order_booking'), 
        ('Movies',  '0002_booking'), 
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking', 
        ), 
    ]
