# Generated by Django 5.1 on 2024-11-07 20:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations,  models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users',  '0002_profile_wallet_balance_alter_profile_role_and_more'), 
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction', 
            fields=[
                ('id',  models.BigAutoField(auto_created=True,  primary_key=True,  serialize=False,  verbose_name='ID')), 
                ('transaction_type',  models.CharField(choices=[('ticket',  'Ticket Booking'),  ('food',  'Food Order')],  max_length=20)), 
                ('amount',  models.DecimalField(decimal_places=2,  max_digits=10)), 
                ('status',  models.CharField(choices=[('INCOMPLETE',  'Incomplete'),  ('COMPLETE',  'Complete'),  ('REVERTED',  'Reverted')],  max_length=10)), 
                ('timestamp',  models.DateTimeField(default=django.utils.timezone.now)), 
                ('receiver_wallet',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  related_name='received_transactions',  to='users.profile')), 
                ('sender_wallet',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  related_name='sent_transactions',  to='users.profile')), 
            ], 
        ), 
    ]
