#  Generated by Django 5.1 on 2024-11-12 16:04

import django.db.models.deletion
from django.db import migrations,  models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings',  '0001_initial'), 
        ('Food',  '0002_alter_order_booking'), 
        ('Transactions',  '0001_initial'), 
    ]

    operations = [
        migrations.AddField(
            model_name='transaction', 
            name='booking', 
            field=models.ForeignKey(blank=True,  default=None,  null=True,  on_delete=django.db.models.deletion.SET_NULL,  related_name='transactions',  to='Bookings.booking'), 
        ), 
        migrations.AddField(
            model_name='transaction', 
            name='order', 
            field=models.ForeignKey(blank=True,  default=None,  null=True,  on_delete=django.db.models.deletion.SET_NULL,  related_name='transactions',  to='Food.order'), 
        ), 
    ]
