#  Generated by Django 5.1.3 on 2024-11-14 08:33

from django.db import migrations,  models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions',  '0002_transaction_booking_transaction_order'), 
    ]

    operations = [
        migrations.AddField(
            model_name='transaction', 
            name='otp', 
            field=models.CharField(blank=True,  max_length=6,  null=True), 
        ), 
    ]
