#  Generated by Django 5.1 on 2024-11-12 16:31

from django.db import migrations,  models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings',  '0001_initial'), 
    ]

    operations = [
        migrations.AddField(
            model_name='booking', 
            name='tickets', 
            field=models.IntegerField(default=0), 
        ), 
    ]
