# Generated by Django 5.1 on 2024-11-07 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations,  models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL), 
    ]

    operations = [
        migrations.CreateModel(
            name='Theater', 
            fields=[
                ('id',  models.BigAutoField(auto_created=True,  primary_key=True,  serialize=False,  verbose_name='ID')), 
                ('name',  models.CharField(max_length=255)), 
                ('location',  models.CharField(max_length=255)), 
                ('admin',  models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,  to=settings.AUTH_USER_MODEL)), 
            ], 
        ), 
        migrations.CreateModel(
            name='Screen', 
            fields=[
                ('id',  models.BigAutoField(auto_created=True,  primary_key=True,  serialize=False,  verbose_name='ID')), 
                ('name',  models.CharField(max_length=255)), 
                ('total_seats',  models.IntegerField()), 
                ('theater',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  to='Theaters.theater')), 
            ], 
        ), 
    ]
