#  Generated by Django 5.1 on 2024-11-11 08:58

import django.db.models.deletion
from django.db import migrations,  models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Movies',  '0002_booking'), 
        ('Theaters',  '0001_initial'), 
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem', 
            fields=[
                ('id',  models.BigAutoField(auto_created=True,  primary_key=True,  serialize=False,  verbose_name='ID')), 
                ('name',  models.CharField(max_length=255)), 
                ('price',  models.DecimalField(decimal_places=2,  max_digits=5)), 
                ('theater',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  to='Theaters.theater')), 
            ], 
        ), 
        migrations.CreateModel(
            name='Order', 
            fields=[
                ('id',  models.BigAutoField(auto_created=True,  primary_key=True,  serialize=False,  verbose_name='ID')), 
                ('quantity',  models.PositiveIntegerField()), 
                ('total_price',  models.DecimalField(decimal_places=2,  max_digits=6)), 
                ('ordered_at',  models.DateTimeField(auto_now_add=True)), 
                ('booking',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  to='Movies.booking')), 
                ('food_item',  models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  to='Food.fooditem')), 
            ], 
        ), 
    ]
