#  Generated by Django 5.1 on 2024-11-11 13:01

import django.db.models.deletion
from django.db import migrations,  models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookings',  '0001_initial'), 
        ('Food',  '0001_initial'), 
    ]

    operations = [
        migrations.AlterField(
            model_name='order', 
            name='booking', 
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,  to='Bookings.booking'), 
        ), 
    ]
